version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "888:80"